dradis: Fix clippy error
`dtd.vbp` is a u16 now and clippy throws this error:

   error: useless conversion to the same type: `u16`
      --> dradis/src/helpers.rs:227:57
       |
   227 |  / u32::from(u16::from(dtd.vfp) + dtd.vdisplay
       |  + u16::from(dtd.vbp) + u16::from(dtd.vsync));
       |    ^^^^^^^^^^ help: consider removing `u16::from()`: `dtd.vbp`
       |
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion

Fixes: 11431b75ff5c ("build(deps): bump redid from `4e966cc` to `862de87`")

Signed-off-by: José Expósito <jose.exposito89@gmail.com>